before_script:
  - echo "no before script"

variables:
  var: "myVar"

stages:
  - build

build:develop:
  stage: build
  script:
    - ls -al
  except:
    - master

build:prod:
  stage: build
  script:
  - ls -al
  only:
    - master

