site_name: Interview
site_url: https://github.com/example
site_description: An example of Documentation as Code. Just topics for technical interview.
site_author: vlcz@seznam.cz
copyright: <b>Updated:</b> GIT_COMMIT_DATE

extra:
  version: 1.1

nav:
# ==========================================================
- Process:
  -



# ==========================================================

theme: readthedocs
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

#theme:
#  name: mkdocs
#  highlightjs: true
#  hljs_languages:
#    - yaml
#    - rust
#  custom_dir: disable-toc

plugins:
  - search

markdown_extensions:
  - smarty
  - sane_lists
